-- Create the author table
CREATE TABLE author (
    author_id INTEGER
    GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Create the publication table
CREATE TABLE publication (
    publication_id INTEGER
    GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Create the books table
CREATE TABLE book (
    book_id INTEGER
    GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    author_id INTEGER NOT NULL,
    genre VARCHAR(100),
    publication_id INTEGER NOT NULL,
    CONSTRAINT fk_author FOREIGN KEY (author_id)
    REFERENCES author(author_id) ON DELETE CASCADE,
    CONSTRAINT fk_publication
    FOREIGN KEY (publication_id)
    REFERENCES publication(publication_id) ON DELETE CASCADE
);

-- Insert data into the author table
INSERT INTO author (name) VALUES ('J.K. Rowling');
INSERT INTO author (name) VALUES ('George R.R. Martin');
INSERT INTO author (name) VALUES ('J.R.R. Tolkien');
INSERT INTO author (name) VALUES ('Agatha Christie');
INSERT INTO author (name) VALUES ('Stephen King');
INSERT INTO author (name) VALUES ('Isaac Asimov');
INSERT INTO author (name) VALUES ('Arthur Conan Doyle');
INSERT INTO author (name) VALUES ('Ernest Hemingway');
INSERT INTO author (name) VALUES ('Jane Austen');
INSERT INTO author (name) VALUES ('Mark Twain');

-- Insert data into the publication table
INSERT INTO publication (name) VALUES ('Bloomsbury');
INSERT INTO publication (name) VALUES ('Bantam Books');
INSERT INTO publication (name) VALUES ('HarperCollins');
INSERT INTO publication (name) VALUES ('Penguin Books');
INSERT INTO publication (name) VALUES ('Simon & Schuster');

-- Insert data into the book table
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Harry Potter and the Philosopher''s Stone', 1, 'Fantasy', 1);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Harry Potter and the Chamber of Secrets', 1, 'Fantasy', 1);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Harry Potter and the Prisoner of Azkaban', 1, 'Fantasy', 1);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Harry Potter and the Goblet of Fire', 1, 'Fantasy', 1);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Harry Potter and the Order of the Phoenix', 1, 'Fantasy', 1);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Game of Thrones', 2, 'Fantasy', 2);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Clash of Kings', 2, 'Fantasy', 2);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Storm of Swords', 2, 'Fantasy', 2);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Feast for Crows', 2, 'Fantasy', 2);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Dance with Dragons', 2, 'Fantasy', 2);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Hobbit', 3, 'Fantasy', 3);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Fellowship of the Ring', 3, 'Fantasy', 3);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Two Towers', 3, 'Fantasy', 3);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Return of the King', 3, 'Fantasy', 3);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Murder on the Orient Express', 4, 'Mystery', 4);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Death on the Nile', 4, 'Mystery', 4);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The ABC Murders', 4, 'Mystery', 4);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Shining', 5, 'Horror', 5);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Carrie', 5, 'Horror', 5);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('It', 5, 'Horror', 5);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Misery', 5, 'Horror', 5);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Foundation', 6, 'Science Fiction', 2);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('I, Robot', 6, 'Science Fiction', 2);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Adventures of Sherlock Holmes', 7, 'Mystery', 3);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Hound of the Baskervilles', 7, 'Mystery', 3);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Old Man and the Sea', 8, 'Fiction', 1);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('A Farewell to Arms', 8, 'Fiction', 1);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Pride and Prejudice', 9, 'Romance', 4);

INSERT INTO book (name, author_id, genre, publication_id) VALUES ('The Adventures of Tom Sawyer', 10, 'Adventure', 5);
INSERT INTO book (name, author_id, genre, publication_id) VALUES ('Adventures of Huckleberry Finn', 10, 'Adventure', 5);

