@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator none
hide empty attributes
skinparam Handwritten false
skinparam ClassBorderColor black
'skinparam BackgroundColor #F0EDDE
skinparam BackgroundColor #f9f5f6
skinparam ClassAttributeFontColor #222222
skinparam ClassFontStyle bold

skinparam class {
ArrowColor #14b8a6
ArrowFontColor #3C88A3
hide empty attributes
skinparam Handwritten false
skinparam ClassBorderColor black
BackgroundColor #FFFFFF
}

interface VectorStore {
  +similaritySearch(String query):List<Document>
  +similaritySearch(SearchRequest request):List<Document>
}

interface ChatModel {
  +call(String):String
}

class OpenAIChatModel {
  +call(String):String
}
class PromptTemplate {
  +PromptTemplate(Resource)
  +create(Map<String,Object>):Prompt
  +render():String
}

class Prompt {
  +getContents():String
}
class Document {
  getContent():String
}


OpenAIChatModel -down-|> ChatModel:implements
ChatModel -down-> Prompt:uses
PromptTemplate -left-> Prompt: creates
VectorStore -up-> Document:uses
PromptTemplate -[hidden]up-> VectorStore
@enduml